# This ConfigMap is used to create the denied packets alerting rules in Prometheus.
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-prometheus-dp-count
  namespace: calico-monitoring
  labels:
    role: calico-prometheus-rules
    prometheus: calico-node-prometheus
data:
  calico.rules.yaml: |+
    groups:
    - name: ./calico.rules
      rules:
      - alert: DeniedPacketsCount
        expr: count_over_time(calico_denied_packets{policy!="security|quarantine|1|deny"}[5s]) > 0
        labels:
          severity: critical
        annotations:
          summary: "Policy {{$labels.policy}} denying packets"
          description: "{{$labels.instance}} is denying packets by policy {{$labels.policy}}."
