
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: whitelist-intra-cluster-in
spec:
  selector: tigera.io/type == "master"
  applyOnForward: true
  order: 20
  types:
  - Ingress
  ingress:
  - action: Allow

