
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: whitelist-intra-cluster-in
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  selector: tigera.io/type == "master"
  order: 20
  ingress:
  - action: Allow

