apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.quarantine
  annotations:
    argocd.argoproj.io/compare-options: "IgnoreExtraneous"
spec:
  tier: security
  order: 100
  selector: quarantine == "true"
  ingress:
  - action: Log
    source: {}
    destination: {}
  - action: Deny
    source: {}
    destination: {}
  egress:
  - action: Log
    source: {}
    destination: {}
  - action: Deny
    source: {}
    destination: {}
  types:
  - Ingress
  - Egress
